### ISSUE TITLE
Problem in installing

### ISSUE THREAD

**Issue by sah-anshu** [rajesh6115/myesme#1]
Hi I am unable to compile this. Can you please guide me instructions,. 

anshu@anshu-lenovo-3000-g530:~/python/myesme-master$ ls -al
total 104
drwxrwxr-x 5 anshu anshu  4096 Nov 22 10:00 .
drwxrwxr-x 9 anshu anshu  4096 Dec  4 17:54 ..
-rw-rw-r-- 1 anshu anshu     0 Nov 22 10:00 AUTHORS
-rw-rw-r-- 1 anshu anshu     0 Nov 22 10:00 ChangeLog
-rw-rw-r-- 1 anshu anshu  1450 Nov 22 10:00 configure.ac
-rw-rw-r-- 1 anshu anshu 35147 Nov 22 10:00 COPYING
-rw-rw-r-- 1 anshu anshu   423 Nov 22 10:00 .gitignore
drwxrwxr-x 2 anshu anshu  4096 Nov 22 10:00 include
-rw-rw-r-- 1 anshu anshu 15752 Nov 22 10:00 INSTALL
-rw-rw-r-- 1 anshu anshu 18027 Nov 22 10:00 LICENSE
drwxrwxr-x 2 anshu anshu  4096 Nov 22 10:00 m4
-rw-rw-r-- 1 anshu anshu    96 Nov 22 10:00 Makefile.am
-rw-rw-r-- 1 anshu anshu     0 Nov 22 10:00 NEWS
-rw-rw-r-- 1 anshu anshu     0 Nov 22 10:00 README
drwxrwxr-x 2 anshu anshu  4096 Nov 22 10:00 src
anshu@anshu-lenovo-3000-g530:~/python/myesme-master$ autoconf
configure.ac:8: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:13: error: possibly undefined macro: AM_PROG_CC_C_O
configure.ac:25: error: possibly undefined macro: AM_PROG_AR
configure.ac:29: error: possibly undefined macro: AC_ENABLE_SHARED
configure.ac:30: error: possibly undefined macro: AC_PROG_LIBTOOL
anshu@anshu-lenovo-3000-g530:~/python/myesme-master$ ls -l
total 220
-rw-rw-r-- 1 anshu anshu      0 Nov 22 10:00 AUTHORS
drwxr-xr-x 2 anshu anshu   4096 Dec  4 17:56 autom4te.cache
-rw-rw-r-- 1 anshu anshu      0 Nov 22 10:00 ChangeLog
-rwxrwxr-x 1 anshu anshu 123848 Dec  4 17:56 configure
-rw-rw-r-- 1 anshu anshu   1450 Nov 22 10:00 configure.ac
-rw-rw-r-- 1 anshu anshu  35147 Nov 22 10:00 COPYING
drwxrwxr-x 2 anshu anshu   4096 Nov 22 10:00 include
-rw-rw-r-- 1 anshu anshu  15752 Nov 22 10:00 INSTALL
-rw-rw-r-- 1 anshu anshu  18027 Nov 22 10:00 LICENSE
drwxrwxr-x 2 anshu anshu   4096 Nov 22 10:00 m4
-rw-rw-r-- 1 anshu anshu     96 Nov 22 10:00 Makefile.am
-rw-rw-r-- 1 anshu anshu      0 Nov 22 10:00 NEWS
-rw-rw-r-- 1 anshu anshu      0 Nov 22 10:00 README
drwxrwxr-x 2 anshu anshu   4096 Nov 22 10:00 src
anshu@anshu-lenovo-3000-g530:~/python/myesme-master$ ./configure 
configure: error: cannot find install-sh, install.sh, or shtool in build-aux "."/build-aux
anshu@anshu-lenovo-3000-g530:~/python/myesme-master$

**Comment by sah-anshu** [comment]
anshu@anshu-lenovo-3000-g530:~/python/myesme-master$ automake --version
automake (GNU automake) 1.14.1
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later http://gnu.org/licenses/gpl-2.0.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey tromey@redhat.com
       and Alexandre Duret-Lutz adl@gnu.org.
anshu@anshu-lenovo-3000-g530:~/python/myesme-master$ autoconf --version
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
http://gnu.org/licenses/gpl.html, http://gnu.org/licenses/exceptions.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
anshu@anshu-lenovo-3000-g530:~/python/myesme-master$

**Comment by rajesh6115** [comment]
Are u following linux standards.
To install use below things
autoreconf -i
./configure -- prefix=/usr
make
sudo make install

**Comment by rajesh6115** [comment]
README file Updated regarding How to Compile and Install.
